name: Tracking Updater

on:
  schedule:
    - cron: "0 */6 * * *"   # a cada 6h
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Remove broken Ubuntu chromedriver
        run: |
          sudo rm -f /usr/bin/chromedriver
          sudo rm -f /snap/bin/chromium.chromedriver || true

      - name: Install Google Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager gspread oauth2client

      - name: Run updater
        run: python tracking_updater/selenium_updater.py
